[View in Colaboratory](https://colab.research.google.com/github/bhavya5491/Machine-Learning/blob/master/Keras_and_IMDB-2.ipynb)

In [0]:
from keras.datasets import imdb

In [0]:
(train_data, train_labels), (test_data, test_labels) = imdb.load_data(num_words=10000)

In [30]:

len(test_data[10])

209

In [31]:
len(train_data[10])

450

In [32]:
train_labels

array([1, 0, 0, ..., 0, 1, 0])

In [33]:
test_labels

array([0, 1, 1, ..., 0, 0, 0])

In [34]:
max([max(sequence) for sequence in train_data])

9999

In [35]:
max([max(sequence) for sequence in test_data])

9999

In [0]:
import numpy as np

In [37]:
# Using one hot encoding manually creating 10,000 dimensions
def vectorize_sequence(data, dimension=10000):
  results = np.zeros((len(data), dimension))
  for i, sequence in enumerate(data):
    results[i, sequence] = 1
  return (results)
x_train = vectorize_sequence(train_data)
x_test = vectorize_sequence(test_data)

x_train.shape

(25000, 10000)

In [38]:
x_test[0]

array([0., 1., 1., ..., 0., 0., 0.])

In [39]:
y_train = np.asarray(train_labels).astype('float32')
y_test = np.asarray(test_labels).astype('float32')
y_test.shape

(25000,)

In [0]:
# Initializing model and layers
from keras import models
from keras import layers

In [0]:
model = models.Sequential()
model.add(layers.Dense(16, activation='relu', input_shape=(10000,)))
model.add(layers.Dense(16, activation='relu'))
model.add(layers.Dense(1, activation='sigmoid'))

In [0]:
#Compiling the model which inlcudes optimizer, loss and metrics used
model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['accuracy'])

In [0]:
#from keras import optimizers
#model.compile(optimizer=optimizers.RMSprop(lr=0.001), loss='binary_crossentropy', metrics=['accuracy'])

In [0]:
#from keras import losses
#from keras import metrics

In [0]:
#model.compile(optimizer=optimizers.RMSprop(lr=0.001), loss=losses.binary_crossentropy, metrics=[metrics.binary_accuracy])

In [0]:
# Dividing the dataset into train and validation set
x_val = x_train[:1000]
partial_x_train = x_train[1000:]
y_val = y_train[:1000]
partial_y_train = y_train[1000:]


In [0]:
#model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['accuracy'])
#history = model.fit(partial_x_train, partial_y_train, epochs=20, batch_size=512, validation_data=(x_val,y_val))

In [0]:
#history_dict = history.history
#history_dict.keys()

In [0]:
#history_dict.values()

In [0]:
import matplotlib.pyplot as plt

In [0]:
#loss_values = history_dict['loss']
#val_loss_values = history_dict['val_loss']
#acc = history_dict['acc']
#epochs = range(1, len(acc) + 1)

#plt.plot(epochs, loss_values, 'bo', label='Training Loss')
#plt.plot(epochs, val_loss_values, 'b', label='Validation Loss')
#plt.title('Training and Validation loss')
#plt.xlabel('Epochs')
#plt.ylabel('Loss')
#plt.legend()
#plt.show()

In [0]:
# Plotting the training and validation accuracy

#plt.clf()
#val_acc = history_dict['val_acc']
#plt.plot(epochs, acc, 'bo', label='Training accuracy')
#plt.plot(epochs, val_acc, 'b', label='Validation accuracy')
#plt.title("Training and Validation accuracy")
#plt.xlabel('Epochs')
#plt.ylabel('Accuracy')
#plt.legend()
#plt.show()

In [53]:
# Case of overfitting as validation accuracy and loss go down after 4 epochs and training accuracy goes to almost 1
# Let's buld a new model with 4 epochs
model.fit(x_train, y_train, epochs=4, batch_size=512)
results = model.evaluate(x_test, y_test)

Epoch 1/4
25000/25000 [==============================] - 2s 89us/step - loss: 0.4479 - acc: 0.8170
Epoch 2/4
25000/25000 [==============================] - 2s 86us/step - loss: 0.2548 - acc: 0.9098
Epoch 3/4
25000/25000 [==============================] - 2s 82us/step - loss: 0.1970 - acc: 0.9296
Epoch 4/4
25000/25000 [==============================] - 2s 76us/step


In [54]:
results

[0.2944350778102875, 0.88368]

In [55]:
model.predict(x_test)

array([[0.2243466 ],
       [0.9997379 ],
       [0.83296376],
       ...,
       [0.1945436 ],
       [0.0645091 ],
       [0.5846836 ]], dtype=float32)