[View in Colaboratory](https://colab.research.google.com/github/bhavya5491/Machine-Learning/blob/master/Keras_and_IMDB.ipynb)

In [1]:
from keras.datasets import imdb

Using TensorFlow backend.


In [0]:
(train_data, train_labels), (test_data, test_labels) = imdb.load_data(num_words=10000)

In [3]:

len(test_data[10])

209

In [4]:
len(train_data[10])

450

In [5]:
train_labels

array([1, 0, 0, ..., 0, 1, 0])

In [6]:
test_labels

array([0, 1, 1, ..., 0, 0, 0])

In [7]:
max([max(sequence) for sequence in train_data])

9999

In [8]:
max([max(sequence) for sequence in test_data])

9999

In [0]:
import numpy as np

In [10]:
def vectorize_sequence(data, dimension=10000):
  results = np.zeros((len(data), dimension))
  for i, sequence in enumerate(data):
    results[i, sequence] = 1
  return (results)
x_train = vectorize_sequence(train_data)
x_test = vectorize_sequence(test_data)

x_train.shape

(25000, 10000)

In [11]:
x_test[0]

array([0., 1., 1., ..., 0., 0., 0.])

In [12]:
y_train = np.asarray(train_labels).astype('float32')
y_test = np.asarray(test_labels).astype('float32')
y_test.shape

(25000,)

In [0]:
from keras import models
from keras import layers

In [0]:
model = models.Sequential()
model.add(layers.Dense(16, activation='relu', input_shape=(10000,)))
model.add(layers.Dense(16, activation='relu'))
model.add(layers.Dense(1, activation='sigmoid'))

In [0]:
model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['accuracy'])

In [0]:
from keras import optimizers
model.compile(optimizer=optimizers.RMSprop(lr=0.001), loss='binary_crossentropy', metrics=['accuracy'])

In [0]:
from keras import losses
from keras import metrics

In [0]:
model.compile(optimizer=optimizers.RMSprop(lr=0.001), loss=losses.binary_crossentropy, metrics=[metrics.binary_accuracy])

In [0]:
x_val = x_train[:1000]
partial_x_train = x_train[1000:]
y_val = y_train[:1000]
partial_y_train = y_train[1000:]


In [0]:
model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['accuracy'])
history = model.fit(partial_x_train, partial_y_train, epochs=20, batch_size=512, validation_data=(x_val,y_val))

In [0]:
history_dict = history.history
history_dict.keys()

In [0]:
history_dict.values()

In [0]:
import matplotlib.pyplot as plt

In [0]:
loss_values = history_dict['loss']
val_loss_values = history_dict['val_loss']
acc = history_dict['acc']
epochs = range(1, len(acc) + 1)

plt.plot(epochs, loss_values, 'bo', label='Training Loss')
plt.plot(epochs, val_loss_values, 'b', label='Validation Loss')
plt.title('Training and Validation loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()
plt.show()

In [0]:
# Plotting the training and validation accuracy

plt.clf()
val_acc = history_dict['val_acc']
plt.plot(epochs, acc, 'bo', label='Training accuracy')
plt.plot(epochs, val_acc, 'b', label='Validation accuracy')
plt.title("Training and Validation accuracy")
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()
plt.show()

In [16]:
# Case of overfitting as validation accuracy and loss go down after 4 epochs and training accuracy goes to almost 1
# Let's buld a new model with 4 epochs
model.fit(x_train, y_train, epochs=4, batch_size=512)
results = model.evaluate(x_test, y_test)

Epoch 1/4
25000/25000 [==============================] - 2s 94us/step - loss: 0.4482 - acc: 0.8173
Epoch 2/4
25000/25000 [==============================] - 2s 95us/step - loss: 0.2549 - acc: 0.9098
Epoch 3/4
25000/25000 [==============================] - 2s 94us/step - loss: 0.1973 - acc: 0.9298
Epoch 4/4
25000/25000 [==============================] - 2s 78us/step


In [17]:
results

[0.29411309955120085, 0.88368]

In [18]:
model.predict(x_test)

array([[0.22901542],
       [0.99972373],
       [0.8295603 ],
       ...,
       [0.1983775 ],
       [0.06487999],
       [0.5629462 ]], dtype=float32)